#pragma once

#define CONSOLEAPP_DEFAULT_RAYTRACING_TARGET_WIDTH 1024
#define CONSOLEAPP_MIN_RAYTRACING_TARGET_WIDTH 4
#define CONSOLEAPP_MAX_RAYTRACING_TARGET_WIDTH 16384

#define CONSOLEAPP_DEFAULT_RAYTRACING_TARGET_HEIGHT 1024
#define CONSOLEAPP_MIN_RAYTRACING_TARGET_HEIGHT 4
#define CONSOLEAPP_MAX_RAYTRACING_TARGET_HEIGHT 16384

#define CONSOLEAPP_DEFAULT_RAYTRACING_TILE_WIDTH 64
#define CONSOLEAPP_DEFAULT_RAYTRACING_TILE_HEIGHT 64

#define CONSOLEAPP_DEFAULT_THREADS 4 //for debug propurses (should be 0 for auto detect)
#define CONSOLEAPP_MIN_THREADS 0
#define CONSOLEAPP_MAX_THREADS 1024

#define CONSOLEAPP_DEFAULT_SAMPLES 1//8
#define CONSOLEAPP_MAX_SAMPLES 1024
#define CONSOLEAPP_SET_SAMPLES_WARNING 128

#define CONSOLEAPP_DEFAULT_BOUNCES 8
#define CONSOLEAPP_MAX_BOUNCES 256
#define CONSOLEAPP_SET_BOUNCES_WARNING 32