#pragma once

#define GUIAPP_WINDOW_SIZE_WIDTH 1280
#define GUIAPP_WINDOW_SIZE_HEIGHT 960

#define GUIAPP_DEFAULT_RAYTRACING_TARGET_WIDTH 1024
#define GUIAPP_MIN_RAYTRACING_TARGET_WIDTH 4
#define GUIAPP_MAX_RAYTRACING_TARGET_WIDTH 16384

#define GUIAPP_DEFAULT_RAYTRACING_TARGET_HEIGHT 1024
#define GUIAPP_MIN_RAYTRACING_TARGET_HEIGHT 4
#define GUIAPP_MAX_RAYTRACING_TARGET_HEIGHT 16384

#define GUIAPP_DEFAULT_RAYTRACING_TILE_WIDTH 64
#define GUIAPP_DEFAULT_RAYTRACING_TILE_HEIGHT 64

#define GUIAPP_DEFAULT_THREADS 4 //for debug propurses (should be 0 for auto detect)
#define GUIAPP_MIN_THREADS 0
#define GUIAPP_MAX_THREADS 1024

#define GUIAPP_DEFAULT_SAMPLES 8
#define GUIAPP_MAX_SAMPLES 1024
#define GUIAPP_SET_SAMPLES_WARNING 128

#define GUIAPP_DEFAULT_BOUNCES 4
#define GUIAPP_MAX_BOUNCES 256
#define GUIAPP_SET_BOUNCES_WARNING 32